### ISSUE TITLE
This is not automatically pulling nanoleaf (https://github.com/software-2/nanoleaf)

### ISSUE THREAD

**Issue by Zstar0** [software-2/ha-aurora#4]
I'm running Home Assistant in a docker and it looks like it can't automatically pull in the needed package for the aurora.py script.  Any ideas?

**Comment by pancho-villa** [comment]
See my comment [here](https://github.com/software-2/ha-aurora/issues/2#issuecomment-317144522)

**Comment by Zstar0** [comment]
Thanks, I was able to install nanoleaf lib manually by attaching to docker as per here: https://askubuntu.com/questions/505506/how-to-get-bash-or-ssh-into-a-running-container-in-background-mode
